importerToolGeomer: KnownSchemaParser Class Reference
KnownSchemaParser Class Reference
Converts any GML file in its corresponding namespace to RDF, with optionally making assumptions about ranges and domains.
Public Member Functions
KnownSchemaParser (OntModel model, Boolean range, Boolean domain, String indnamespace) throws IOException
void startPrefixMapping (String prefix, String uri) throws SAXException
void startElement (String uri, String localName, String qName, Attributes attributes) throws SAXException
void characters (char[] ch, int start, int length) throws SAXException
void endElement (String uri, String localName, String qName) throws SAXException
void endPrefixMapping (String prefix) throws SAXException
void setDocumentLocator (Locator locator)
void startDocument () throws SAXException
void endDocument () throws SAXException
void ignorableWhitespace (char[] ch, int start, int length) throws SAXException
void processingInstruction (String target, String data) throws SAXException
void skippedEntity (String name) throws SAXException
Static Public Member Functions
static String formatWKTString (String str, char c, int n)
static void restructureDomains (OntModel model)
Public Attributes
OntModel model
Static Public Attributes
static final String NSGEO = "http://www.opengis.net/ont/geosparql#"
static final String NSSF = "http://www.opengis.net/ont/sf#"
static final String GML = "gml"
static final String WKT = "asWKT"
static final String ASGML = "asGML"
static final String WKTLiteral = "wktLiteral"
static final String NAME = "name"
static final String TYPE = "type"
static final String GMLLiteral = "gmlLiteral"
static final String hasGeometry = "hasGeometry"
static final String XMLSchema ="http://www.w3.org/2001/XMLSchema#"
static final String RDFSchema ="http://www.w3.org/2000/01/rdf-schema#"
static final String Envelope ="Envelope"
static final String Corner ="Corner"
Package Attributes
final List< String > openedTags2
Boolean inClass
Boolean envelope
final Stack< String > stack2
Boolean domain = false
String stringAttribute =""
Private Member Functions
Map< String, String > restrictedTypes (String classType)
Literal determineLiteralType (String literal)
Private Attributes
final Map< String, OntResource > knownMappings
Individual currentIndividual
Individual lastlinkedIndividual
String currentType
Map< String, String > currentRestrictions
final List< String > openedTags
Boolean featureMember
final StringBuilder multipleChildrenBuffer
final StringBuilder gmlStrBuilder
String codeSpace = ""
final Stack< String > stack
final Stack< Map< String, String > > restrictionStack
Integer outertagCounter
Integer splitterCountThreshold = 0
final StringBuilder attbuilder
final SimpleDateFormat parserSDF1 = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss")
final SimpleDateFormat parserSDF2 = new SimpleDateFormat("yyyy-MM-dd")
Boolean range = false
final StringBuilder literalBuffer =new StringBuilder()
boolean alreadyHandled
OntClass codelist
Attributes attributes
String uuid =UUID.randomUUID().toString()
String indnamespace
Static Private Attributes
static final String TRUE = "true"
static final String FALSE = "false"
static final String POINT = "Point"
static final String HTTP = "http://"
static final String HTTP2 = "http"
static final String gmlid = "gml:id"
static final String HTTPS = "https://"
static final String HTTPS2 = "https"
static Set< String > featureMembers
static final String XLINKHREF = "xlink:href"
static final String CODESPACE = "codeSpace"
Detailed Description
Converts any GML file in its corresponding namespace to RDF, with optionally making assumptions about ranges and domains.
Author
timo.homburg
Constructor & Destructor Documentation
KnownSchemaParser()
KnownSchemaParser (OntModel model, Boolean range, Boolean domain, String indnamespace) throws IOException
References KnownSchemaParser.domain, KnownSchemaParser.indnamespace, KnownSchemaParser.model, and KnownSchemaParser.range.
{
                 this.model = model;
                 this.codelist = model.createClass("http://semgis.de/geodata#Codelist");
                 this.outertagCounter = 0;
                 this.envelope = false;
                 this.knownMappings = new TreeMap<String, OntResource>();
                 this.openedTags = new LinkedList<String>();
                 this.openedTags2 = new LinkedList<String>();
                 this.featureMember = false;
                 this.inClass = false;
                 this.multipleChildrenBuffer = new StringBuilder();
                 this.gmlStrBuilder = new StringBuilder();
                 this.attbuilder = new StringBuilder();
                 this.currentRestrictions = new TreeMap<String, String>();
                 this.stack = new Stack<String>();
                 this.indnamespace=indnamespace;
                 this.stack2 = new Stack<String>();
                 this.range = range;
                 this.domain = domain;
                 this.restrictionStack = new Stack<Map<String, String>>();
         }
Member Function Documentation
characters()
void characters (char [] ch, int start, int length) throws SAXException
References KnownSchemaParser.currentIndividual, KnownSchemaParser.determineLiteralType(), KnownSchemaParser.formatWKTString(), and KnownSchemaParser.stringAttribute.
{
                 // if(outertagCounter>beginProcessing){
                 String literal = new String(ch, start, length);
                 literalBuffer.append(literal.trim());
                  if (featureMember && openedTags.size() > 1 && !literal.trim().isEmpty() ) {
                          if(openedTags.get(openedTags.size() - 1).contains("value")) {
                                         //this.stringAttributeBool=false;
                                         System.out.println("StringAttribute Adding: "+this.stringAttribute+" - "+literal);
                                         currentIndividual.addProperty(model.createDatatypeProperty(this.stringAttribute),
                                                         this.determineLiteralType(literal));
                                         this.stringAttribute="";
                                         this.alreadyHandled=true;
                                 }else if (knownMappings.get(openedTags.get(openedTags.size() - 1)) != null
                                         && knownMappings.get(openedTags.get(openedTags.size() - 1)).isObjectProperty()
                                         && this.currentRestrictions.containsKey(openedTags.get(openedTags.size() - 1))
                                         && !this.currentRestrictions.get(openedTags.get(openedTags.size() - 1))
                                                         .contains(XMLSchema)
                                         && StringUtils.isNumeric(literal)) {
                                 this.currentIndividual.addProperty(model.getObjectProperty(openedTags.get(openedTags.size() - 1)),
                                                 model.getIndividual(
                                                                 this.currentRestrictions.get(openedTags.get(openedTags.size() - 1)) + "_" + literal));
                                 alreadyHandled = true;
                         } else if (openedTags.get(openedTags.size() - 1).contains(Corner)
                                         && stack2.lastElement().contains(Envelope)) {
                                 multipleChildrenBuffer.append("<").append(openedTags2.get(openedTags2.size() - 1)).append(">")
                                                 .append(literal).append("</").append(openedTags2.get(openedTags2.size() - 1)).append(">");
                                 alreadyHandled = true;
                         } else if (openedTags.get(openedTags.size() - 1).contains("posList") || openedTags.get(openedTags.size() - 1).contains("coordinates")
                                         || openedTags.get(openedTags.size() - 1).contains("pos")) {
                                 String wktlit = this.currentIndividual.getRDFType().getLocalName() + "(" + literal + ")";
                                 this.gmlStrBuilder.delete(0, gmlStrBuilder.length());
                                 gmlStrBuilder.append("<").append(stack2.lastElement()).append(" xmlns:gml=\"")
                                                 .append(stack.lastElement().substring(0, stack.lastElement().lastIndexOf('#'))).append("\"><")
                                                 .append(openedTags2.get(openedTags2.size() - 1)).append(">").append(literal).append("</")
                                                 .append(openedTags2.get(openedTags2.size() - 1)).append("></").append(stack2.lastElement())
                                                 .append(">");
                                 String gmlStr = gmlStrBuilder.toString();
                                 // System.out.println("gmlStr: "+gmlStr);
                                 if(this.lastlinkedIndividual!=null) {
                                         this.lastlinkedIndividual.addProperty(this.model.createObjectProperty(NSGEO + hasGeometry),this.currentIndividual);
                                         this.lastlinkedIndividual=null;
                                 }
                                 this.currentIndividual.addProperty(this.model.createDatatypeProperty(NSGEO + ASGML),
                                                 this.model.createTypedLiteral(gmlStr, NSGEO + GMLLiteral));
                                 if (!wktlit.contains(POINT))
                                         wktlit = formatWKTString(wktlit, ' ', 2);
                                 try {
                                         wktlit=wktlit.replace(","," ");
                                         //com.vividsolutions.jts.geom.Geometry geom = (com.vividsolutions.jts.geom.Geometry) wktreader
                                         //              .read(wktlit);
                                         if(this.lastlinkedIndividual!=null) {
                                                 this.lastlinkedIndividual.addProperty(this.model.createObjectProperty(NSGEO + hasGeometry),this.currentIndividual);
                                                 this.lastlinkedIndividual=null;
                                         }
                                         this.currentIndividual.addProperty(this.model.createDatatypeProperty(NSGEO + WKT),
                                                         this.model.createTypedLiteral(wktlit, NSGEO + WKTLiteral));
                                 } catch (Exception e) {
                                         e.printStackTrace();
                                 }
                                 alreadyHandled = true;
                         }
                 }
                 /*if(!this.stringAttribute.isEmpty()) {
                         this.stringAttributeBool=true;
                 }else {
                         this.stringAttributeBool=false;
                 }*/
         }
determineLiteralType()
Literal determineLiteralType (String literal) private
Referenced by KnownSchemaParser.characters(), KnownSchemaParser.endElement(), and KnownSchemaParser.startElement().
{
                 try {
                         if (StringUtils.isNumeric(literal) && !literal.contains(".")) {
                                 return this.model.createTypedLiteral(Integer.valueOf(literal), XSD.xint.getURI());
                         } else if (StringUtils.isNumeric(literal) && literal.contains(".")) {
                                 Double d = Double.valueOf(literal);
                                 return this.model.createTypedLiteral(d, XSD.xdouble.getURI());
                         }
                 } catch (Exception e) {
                 }
                 // System.out.println("DETERMINE LITERAL TYPE - "+literal);
                 try {
                         Date date = parserSDF1.parse(literal);
                         // System.out.println("DETERMINE LITERAL TYPE DATE? "+date);
                         if (date != null) {
                                 String dateStr = parserSDF1.format(date);
                                 return this.model.createTypedLiteral(dateStr, XSD.dateTime.getURI());
                         }
                 } catch (Exception e) {
                 }
                 try {
                         Date date = parserSDF2.parse(literal);
                         // System.out.println("DETERMINE LITERAL TYPE DATE? "+date);
                         if (date != null) {
                                 String dateStr = parserSDF1.format(date);
                                 return this.model.createTypedLiteral(dateStr, XSD.date.getURI());
                         }
                 } catch (Exception e) {
                 }
                 if (TRUE.equals(literal) || FALSE.equals(literal)) {
                         return this.model.createTypedLiteral(Boolean.valueOf(literal), XSD.xboolean.getURI());
                 } else {
                         return this.model.createTypedLiteral(literal, XSD.xstring.getURI());
                 }
         }
endDocument()
void endDocument () throws SAXException
{
                 // TODO Auto-generated method stub
         }
endElement()
void endElement (String uri, String localName, String qName) throws SAXException
References KnownSchemaParser.currentIndividual, KnownSchemaParser.determineLiteralType(), KnownSchemaParser.domain, KnownSchemaParser.GMLLiteral, and KnownSchemaParser.HTTP2.
{
                 String comb = uri + "#" + localName;
                 comb = comb.replace("##", "#");
                 String literal = literalBuffer.toString();
                 if (!alreadyHandled && !openedTags.isEmpty()) {
                         if (!literal.isEmpty()) {
                                 if (knownMappings.get(openedTags.get(openedTags.size() - 1)) != null
                                                 && knownMappings.get(openedTags.get(openedTags.size() - 1)).isAnnotationProperty()) {
                                         this.currentIndividual.addProperty(
                                                         model.createAnnotationProperty(openedTags.get(openedTags.size() - 1)),
                                                         this.model.createOntResource(literal));
                                         alreadyHandled=true;
                                 } else if (knownMappings.get(openedTags.get(openedTags.size() - 1)) != null
                                                 && knownMappings.get(openedTags.get(openedTags.size() - 1)).isDatatypeProperty()) {
                                         if (!codeSpace.isEmpty()) {
                                                                 if(literal.contains(HTTP) || literal.contains(HTTPS)) {
                                                                         this.currentIndividual.addProperty(model.createObjectProperty(openedTags.get(openedTags.size() - 1)),codelist.createIndividual(literal));
                                                                 }else {
                                                                         this.currentIndividual.addProperty(model.createObjectProperty(openedTags.get(openedTags.size() - 1)),codelist.createIndividual(codeSpace + literal));
                                                                 }
                                         } else {
                                                 Literal liter = this.determineLiteralType(literal);
                                                 this.currentIndividual.addProperty(
                                                                 model.createDatatypeProperty(openedTags.get(openedTags.size() - 1)), liter);
                                                 if (domain)
                                                         model.getDatatypeProperty(openedTags.get(openedTags.size() - 1))
                                                                         .addDomain(this.currentIndividual.getRDFType());
                                                 if (range)
                                                         model.getDatatypeProperty(openedTags.get(openedTags.size() - 1))
                                                                         .addRange(model.getResource(liter.getDatatypeURI()));
                                                 model.createAllValuesFromRestriction(this.currentIndividual.getRDFType().getURI(),
                                                                 model.getDatatypeProperty(openedTags.get(openedTags.size() - 1)),
                                                                 model.getResource(liter.getDatatypeURI()));
                                         }
                                         alreadyHandled=true;
                                 } else if (knownMappings.get(openedTags.get(openedTags.size() - 1)) != null
                                                 && knownMappings.get(openedTags.get(openedTags.size() - 1)).isProperty()) {
                                         if (!codeSpace.isEmpty()) {
                                                 if(literal.contains(HTTP) || literal.contains(HTTPS)) {
                                                         this.currentIndividual.addProperty(model.createObjectProperty(openedTags.get(openedTags.size() - 1)),codelist.createIndividual(literal));
                                                 }else {
                                                         this.currentIndividual.addProperty(model.createObjectProperty(openedTags.get(openedTags.size() - 1)),codelist.createIndividual(codeSpace + literal));
                                                 }
                                         } else {
                                                 this.currentIndividual.addProperty(
                                                                 model.createDatatypeProperty(openedTags.get(openedTags.size() - 1)),
                                                                 this.determineLiteralType(literal));
                                         }
                                         alreadyHandled=true;
                                 }
                         }
                 }
                 if(openedTags.size() % 2 == 0 && !alreadyHandled && !stack.isEmpty() && !openedTags.isEmpty()
                                  && literal.isEmpty() && attributes.getLength()>1) {
                                 OntClass cls=model.createClass(uuid);
                                 Individual ind=cls.createIndividual(UUID.randomUUID().toString());
                                 //System.out.println((openedTags.get(openedTags.size() - 1)));
                                 //System.out.println(openedTags.get(openedTags.size() - 1)+" Literal is empty "+attributes.getLength());
                                 int i=0;
                                 while(i<attributes.getLength()) {
                                         //System.out.println(openedTags.get(openedTags.size() - 1)+" - "
                                 //+attributes.getLocalName(i)+" - "+attributes.getValue(i));
                                         ind.addProperty(model.createDatatypeProperty(attributes.getLocalName(i)),
                                                         determineLiteralType(attributes.getValue(i)));
                                         i++;
                                 }
                                 this.currentIndividual.addProperty(
                                                 model.createObjectProperty(openedTags.get(openedTags.size() - 1)),
                                                 ind);
                                 this.lastlinkedIndividual=this.currentIndividual;
                 }
                 // System.out.println("Remove: "+uri+localName+ this.openedTags.contains(comb)+"
                 // - "+this.openedTags.size());
                 this.openedTags.remove(comb);
                 // System.out.println("After removal: "+this.openedTags.size());
                 this.openedTags2.remove(qName);
                 // if(outertagCounter>beginProcessing){
                 // System.out.println("OpenedTags: "+openedTags);
                 if (openedTags.size() % 2 == 0 && !stack.isEmpty())
                 {
                         if (localName.contains("Envelop")) {
                                 this.envelope = false;
                                 this.multipleChildrenBuffer.append("</").append(qName).append(">");
                                 if(this.lastlinkedIndividual!=null)
                                         this.lastlinkedIndividual.addProperty(this.model.createObjectProperty(NSGEO + hasGeometry),this.currentIndividual);
                                 this.currentIndividual.addProperty(this.model.createDatatypeProperty(NSGEO + ASGML),
                                                 this.model.createTypedLiteral(multipleChildrenBuffer.toString(), GMLLiteral));
                         }
                         String lastElement = stack.pop();
                         //System.out.println(lastElement);
                         //System.out.println(stack.toString());
                         //System.out.println(stack2.toString());
                         stack2.pop();
                         restrictionStack.pop();
                         if (!stack.isEmpty()) {
                                 int count=StringUtils.countMatches(stack.lastElement(), HTTP2);
                                 if(count>1) {
                                         String indid=stack.lastElement().substring(stack.lastElement().lastIndexOf(HTTP2));
                                         this.currentIndividual = this.model.getIndividual(stack.lastElement());
                                 }else {
                                         this.currentIndividual = this.model.getIndividual(stack.lastElement());
                                 }
                                 // System.out.println("endElement addProperty: "+lastElement);
                                 this.currentIndividual.addProperty(
                                                 this.model.createObjectProperty(this.openedTags.get(this.openedTags.size() - 1)),
                                                 this.model.getIndividual(lastElement));
                                 if (domain)
                                         model.getObjectProperty(this.openedTags.get(this.openedTags.size() - 1))
                                                         .addDomain(this.currentIndividual.getRDFType());
                         }
                         if (!restrictionStack.isEmpty())
                                 this.currentRestrictions = restrictionStack.lastElement();
                         alreadyHandled=true;
                 }
                 if (featureMembers.contains(localName)) {
                         System.out.println("FINISHED=============================================");
                         System.out.println(lastlinkedIndividual);
                         System.out.println(literalBuffer);
                         this.featureMember = false;
                 }
                 /*if(localName.contains("stringAttribute")) {
                         stringAttributeBool=false;
                 }*/
                 if ((uri + "#" + localName).equals(currentType)) {
                         this.inClass = false;
                 }
                 this.codeSpace = "";
         }
endPrefixMapping()
void endPrefixMapping (String prefix) throws SAXException
{
         }
formatWKTString()
static String formatWKTString (String str, char c, int n) static
Referenced by KnownSchemaParser.characters().
{
                 // System.out.println(str);
                 int pos = str.indexOf(c, 0);
                 if (StringUtils.countMatches(str, " ") <= 1)
                         return str;
                 StringBuilder builder = new StringBuilder();
                 boolean second = true;
                 int lastpos = 0;
                 while (pos != -1) {
                         pos = str.indexOf(c, pos + 1);
                         if (!second)
                                 second = true;
                         else if (pos != -1) {
                                 second = false;
                                 builder.append(str.substring(lastpos, pos)).append(",");
                                 lastpos = pos;
                         }
                 }
                 // System.out.println("Lastpos: "+lastpos+" - "+str.length());
                 builder.delete(builder.length() - 1, builder.length());
                 builder.append(str.substring(lastpos, str.length()));
                 return builder.toString();
         }
ignorableWhitespace()
void ignorableWhitespace (char [] ch, int start, int length) throws SAXException
{
                 // TODO Auto-generated method stub
         }
processingInstruction()
void processingInstruction (String target, String data) throws SAXException
{
                 // TODO Auto-generated method stub
         }
restrictedTypes()
Map<String, String> restrictedTypes (String classType) private
{
                 Map<String, String> restrictedTypes = new TreeMap<String, String>();
                 Queue<String> superClasses = new LinkedList<String>();
                 ExtendedIterator<OntClass> supers = this.model.getOntClass(classType).listSuperClasses(true);
                 while (supers.hasNext()) {
                         OntClass superClass = supers.next();
                         if (superClass.isRestriction() && superClass.asRestriction().isAllValuesFromRestriction()) {
                                 OntProperty prop = superClass.asRestriction().getOnProperty();
                                 restrictedTypes.put(prop.getURI(),
                                                 ((OntClass) superClass.asRestriction().asAllValuesFromRestriction().getAllValuesFrom())
                                                                 .getURI());
                         } else if (superClass.isClass() && superClass.getURI() != null) {
                                 // System.out.println("New SuperClass: "+superClass.toString());
                                 superClasses.add(superClass.toString());
                         }
                 }
                 supers.close();
                 if (!superClasses.isEmpty()) {
                         while (!superClasses.isEmpty()) {
                                 String cls = superClasses.poll();
                                 supers = this.model.getOntClass(cls).listSuperClasses(true);
                                 while (supers.hasNext()) {
                                         OntClass superClass = supers.next();
                                         if (superClass.isRestriction() && superClass.asRestriction().isAllValuesFromRestriction()) {
                                                 OntProperty prop = superClass.asRestriction().getOnProperty();
                                                 restrictedTypes.put(prop.getURI(),
                                                                 ((OntClass) superClass.asRestriction().asAllValuesFromRestriction().getAllValuesFrom())
                                                                                 .getURI());
                                         } else if (superClass.isClass() && superClass.getURI() != null) {
                                                 // System.out.println("New SuperClass: "+superClass.toString());
                                                 superClasses.add(superClass.getURI());
                                         }
                                 }
                                 supers.close();
                         }
                 }
                 return restrictedTypes;
         }
restructureDomains()
static void restructureDomains (OntModel model) static
Referenced by GMLImporter.processFile().
{
                 ExtendedIterator<ObjectProperty> objprops = model.listObjectProperties();
                 while (objprops.hasNext()) {
                         ObjectProperty prop=objprops.next();
                         ExtendedIterator<? extends OntResource> domains = prop.listDomain();
                         List<RDFNode> elements = new LinkedList<RDFNode>();
                         List<RDFNode> elements2 = new LinkedList<RDFNode>();
                         Boolean first = true, second = true;
                         if (domains.hasNext())
                                 while (domains.hasNext()) {
                                         if (second && !first) {
                                                 second = false;
                                         }
                                         if (first) {
                                                 first = false;
                                         }
                                         OntResource curdom = domains.next();
                                         if (!curdom.getURI().contains(RDFSchema)
                                                         && !curdom.getURI().contains(OWL.NS))
                                                 elements.add(curdom);
                                 }
                         if (!second)
                                 prop.setDomain(
                                                 model.createUnionClass(null, model.createList(elements.toArray(new RDFNode[elements.size()]))));
                         domains.close();
                         first = true;
                         second = true;
                         ExtendedIterator<? extends OntResource> ranges = prop.listRange();
                         while (ranges.hasNext()) {
                                 if (second && !first) {
                                         second = false;
                                 }
                                 if (first) {
                                         first = false;
                                 }
                                 OntResource curran = ranges.next();
                                 if (!curran.getURI().contains(RDFSchema)
                                                 && !curran.getURI().contains(OWL.NS))
                                         elements2.add(curran);
                         }
                         if (!second)
                                 prop.setRange(model.createUnionClass(null,
                                                 model.createList(elements2.toArray(new RDFNode[elements2.size()]))));
                         ranges.close();
                 }
                 ExtendedIterator<DatatypeProperty> dataprops = model.listDatatypeProperties();
                 while (dataprops.hasNext()) {
                         DatatypeProperty prop2 = dataprops.next();
                         ExtendedIterator<? extends OntResource> domains2 = prop2.listDomain();
                         List<RDFNode> doms = new LinkedList<RDFNode>();
                         List<RDFNode> rgs = new LinkedList<RDFNode>();
                         Boolean first = true, second = true;
                         while (domains2.hasNext()) {
                                 if (second && !first) {
                                         second = false;
                                 }
                                 if (first) {
                                         first = false;
                                 }
                                 OntResource curdom = domains2.next();
                                 if (curdom.getURI() != null && !curdom.getURI().contains(RDFSchema)
                                                 && !curdom.getURI().contains(OWL.NS))
                                         doms.add(curdom);
                                 // domains.add(domains2.next());
                         }
                         if (!second)
                                 prop2.setDomain(model.createUnionClass(null, model.createList(doms.toArray(new RDFNode[doms.size()]))));
                         domains2.close();
                         first = true;
                         second = true;
                         ExtendedIterator<? extends OntResource> ranges2 = prop2.listRange();
                         while (ranges2.hasNext()) {
                                 if (second && !first) {
                                         second = false;
                                 }
                                 if (first) {
                                         first = false;
                                 }
                                 OntResource curran = ranges2.next();
                                 if (!curran.getURI().contains(RDFSchema)
                                                 && !curran.getURI().contains(OWL.NS))
                                         rgs.add(curran);
                         }
                         if (!second)
                                 prop2.setRange(model.createUnionClass(null, model.createList(rgs.toArray(new RDFNode[rgs.size()]))));
                         ranges2.close();
                 }
                 dataprops.close();
         }
setDocumentLocator()
void setDocumentLocator (Locator locator)
{
                 // TODO Auto-generated method stub
         }
skippedEntity()
void skippedEntity (String name) throws SAXException
{
                 // TODO Auto-generated method stub
         }
startDocument()
void startDocument () throws SAXException
{
                 // TODO Auto-generated method stub
         }
startElement()
void startElement (String uri, String localName, String qName, Attributes attributes) throws SAXException
References KnownSchemaParser.attributes, KnownSchemaParser.currentIndividual, KnownSchemaParser.determineLiteralType(), and KnownSchemaParser.domain.
{
                 this.attributes = attributes;
                 //System.out.println(localName);
                 alreadyHandled = false;
                 if (featureMember) {
                         System.out.println(stack);
                         System.out.println(stack2);
                         System.out.println(openedTags);
                         System.out.println(openedTags2);
                         String uriString = uri + "#" + localName;
                         uriString = uriString.replace("##", "#");
                         if (!knownMappings.containsKey(uriString) && openedTags.size() % 2 != 1) {
                                 knownMappings.put(uriString, model.createClass(uriString));
                         } else if (!knownMappings.containsKey(uriString)) {
                                 knownMappings.put(uriString, model.createOntProperty(uriString));
                         }
                         // System.out.println("Add: "+uriString);
                         this.openedTags.add(uriString);
                         this.openedTags2.add(qName);
                         // System.out.println("OpenedTags: "+openedTags);
                         String value;
                         if (attributes.getValue(gmlid) == null) {
                                 value = UUID.randomUUID().toString();
                         } else {
                                 value = attributes.getValue(gmlid);
                         }
                         if (attributes.getValue(CODESPACE) != null)
                                 this.codeSpace = attributes.getValue(CODESPACE);
                         String indid = (uri + "#" + value).replace("##", "#");
                         if (knownMappings.get(uriString) != null && knownMappings.get(uriString).isClass()
                                         && (!inClass || openedTags.size() > 2)) {
                                 this.inClass = true;
                                 if (openedTags.size() % 2 != 0) {
                                         int count=StringUtils.countMatches(indid, HTTP2);
                                         if(count>1) {
                                                 indid=indid.substring(indid.lastIndexOf(HTTP2));
                                                 if(!indnamespace.isEmpty()) {
                                                         indid=indnamespace+indid.substring(indid.lastIndexOf('/')+1);
                                                 }
                                         }
                                         //System.out.println(indid);
                                         this.currentIndividual = model.createIndividual(indid, model.createOntResource(indid));
                                         this.currentIndividual.setRDFType(model.createClass(uriString));
                                         this.currentType = uriString;
                                         if (uriString.contains("Envelop")) {
                                                 this.envelope = true;
                                                 this.multipleChildrenBuffer.delete(0, this.multipleChildrenBuffer.length());
                                                 this.attbuilder.delete(0, this.attbuilder.length());
                                                 attbuilder.append("<");
                                                 attbuilder.append(qName);
                                                 attbuilder.append(" xmlns:gml=\"").append(uri).append("\"");
                                                 for (int i = 0; i < attributes.getLength(); i++) {
                                                         attbuilder.append(" ").append(attributes.getLocalName(i)).append("=\"")
                                                                         .append(attributes.getValue(i) + "\"");
                                                 }
                                                 attbuilder.append(">");
                                                 this.multipleChildrenBuffer.append(attbuilder.toString());
                                         }
                                         // if(stack.isEmpty())
                                         stack.push(this.currentIndividual.toString());
                                         stack2.push(qName);
                                         //System.out.println(stack);
                                         //System.out.println(stack2);
                                         if (attributes.getLength() > 0)
                                                 this.currentIndividual.addLabel(value, "en");
                                         if (attributes.getLength() > 1) {
                                                 for (int i = 0; i < attributes.getLength(); i++) {
                                                         Literal liter = this.determineLiteralType(attributes.getValue(i));
                                                         this.currentIndividual.addProperty(
                                                                         model.createDatatypeProperty(uri + "#" + attributes.getQName(i)), liter);
                                                         if (domain)
                                                                 model.createDatatypeProperty(uri + "#" + attributes.getQName(i))
                                                                                 .addDomain(this.currentIndividual.getRDFType());
                                                         if (range)
                                                                 model.createDatatypeProperty(uri + "#" + attributes.getQName(i))
                                                                                 .addRange(model.getResource(liter.getDatatypeURI()));
                                                 }
                                         }
                                         this.restrictionStack.push(this.currentRestrictions);
                                 }
                         } else {
                                 // System.out.println("Property: "+qName);
                         }
                         if (attributes.getValue(XLINKHREF) != null) {
                                 String linkString;
                                 if (!attributes.getValue(XLINKHREF).startsWith(HTTP) && !attributes.getValue(XLINKHREF).startsWith(HTTPS)) {
                                         linkString = uri + attributes.getValue(XLINKHREF);
                                 } else {
                                         linkString = attributes.getValue(XLINKHREF);
                                 }
                                 Individual propInd;
                                 if (this.model.getIndividual(linkString) == null) {
                                         int count=StringUtils.countMatches(linkString, HTTP2);
                                         if(count>1) {
                                                 String indid2=linkString.substring(linkString.lastIndexOf(HTTP2));
                                                 propInd = model.createIndividual(indid2, this.model.createOntResource(linkString));
                                         }else {
                                                 propInd = model.createIndividual(linkString, this.model.createOntResource(linkString));
                                         }
                                         this.currentIndividual
                                                         .addProperty(model.createObjectProperty(openedTags.get(openedTags.size() - 1)), propInd);
                                         this.lastlinkedIndividual=this.currentIndividual;
                                         if (domain)
                                                 model.getObjectProperty(openedTags.get(openedTags.size() - 1))
                                                                 .addDomain(this.currentIndividual.getRDFType());
                                 } else {
                                         propInd = model.getIndividual(linkString);
                                         this.currentIndividual
                                                         .addProperty(model.createObjectProperty(openedTags.get(openedTags.size() - 1)), propInd);
                                         this.lastlinkedIndividual=this.currentIndividual;
                                         if (domain)
                                                 model.getObjectProperty(openedTags.get(openedTags.size() - 1))
                                                                 .addDomain(this.currentIndividual.getRDFType());
                                         if (range)
                                                 model.getObjectProperty(openedTags.get(openedTags.size() - 1)).addRange(propInd.getRDFType());
                                         model.createAllValuesFromRestriction(this.currentIndividual.getRDFType().getURI(),
                                                         model.getObjectProperty(openedTags.get(openedTags.size() - 1)), propInd.getRDFType());
                                 }
                         }
                 }
                 if (featureMembers.contains(localName)) {
                         this.featureMember = true;
                         outertagCounter++;
                         splitterCountThreshold++;
                         if (splitterCountThreshold == 1000) {
                                 splitterCountThreshold = 0;
                         }
                 }
                 literalBuffer.delete(0,literalBuffer.length());
         }
startPrefixMapping()
void startPrefixMapping (String prefix, String uri) throws SAXException
{
                 // TODO Auto-generated method stub
         }
Member Data Documentation
alreadyHandled
boolean alreadyHandled private
ASGML
final String ASGML = "asGML" static
attbuilder
final StringBuilder attbuilder private
attributes
Attributes attributes private
Referenced by KnownSchemaParser.startElement().
codelist
OntClass codelist private
CODESPACE
final String CODESPACE = "codeSpace" static private
codeSpace
String codeSpace = "" private
Corner
final String Corner ="Corner" static
currentIndividual
Individual currentIndividual private
Referenced by KnownSchemaParser.characters(), KnownSchemaParser.endElement(), and KnownSchemaParser.startElement().
currentRestrictions
Map<String, String> currentRestrictions private
currentType
String currentType private
domain
Boolean domain = false package
Referenced by KnownSchemaParser.endElement(), KnownSchemaParser.KnownSchemaParser(), and KnownSchemaParser.startElement().
Envelope
final String Envelope ="Envelope" static
envelope
Boolean envelope package
FALSE
final String FALSE = "false" static private
featureMember
Boolean featureMember private
featureMembers
Set<String> featureMembers static private
Initial value:
= new TreeSet<String>(
                        Arrays.asList(new String[] { "featureMember", "member", "cityObjectMember" }))
GML
final String GML = "gml" static
gmlid
final String gmlid = "gml:id" static private
GMLLiteral
final String GMLLiteral = "gmlLiteral" static
Referenced by KnownSchemaParser.endElement().
gmlStrBuilder
final StringBuilder gmlStrBuilder private
hasGeometry
final String hasGeometry = "hasGeometry" static
HTTP
final String HTTP = "http://" static private
HTTP2
final String HTTP2 = "http" static private
Referenced by KnownSchemaParser.endElement().
HTTPS
final String HTTPS = "https://" static private
HTTPS2
final String HTTPS2 = "https" static private
inClass
Boolean inClass package
indnamespace
String indnamespace private
Referenced by KnownSchemaParser.KnownSchemaParser().
knownMappings
final Map<String, OntResource> knownMappings private
lastlinkedIndividual
Individual lastlinkedIndividual private
literalBuffer
final StringBuilder literalBuffer =new StringBuilder() private
model
OntModel model
Referenced by KnownSchemaParser.KnownSchemaParser(), and GMLImporter.processFile().
multipleChildrenBuffer
final StringBuilder multipleChildrenBuffer private
NAME
final String NAME = "name" static
NSGEO
final String NSGEO = "http://www.opengis.net/ont/geosparql#" static
NSSF
final String NSSF = "http://www.opengis.net/ont/sf#" static
openedTags
final List<String> openedTags private
openedTags2
final List<String> openedTags2 package
outertagCounter
Integer outertagCounter private
parserSDF1
final SimpleDateFormat parserSDF1 = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss") private
parserSDF2
final SimpleDateFormat parserSDF2 = new SimpleDateFormat("yyyy-MM-dd") private
POINT
final String POINT = "Point" static private
range
Boolean range = false private
Referenced by KnownSchemaParser.KnownSchemaParser().
RDFSchema
final String RDFSchema ="http://www.w3.org/2000/01/rdf-schema#" static
restrictionStack
final Stack<Map<String, String> > restrictionStack private
splitterCountThreshold
Integer splitterCountThreshold = 0 private
stack
final Stack<String> stack private
stack2
final Stack<String> stack2 package
stringAttribute
String stringAttribute ="" package
Referenced by KnownSchemaParser.characters().
TRUE
final String TRUE = "true" static private
TYPE
final String TYPE = "type" static
uuid
String uuid =UUID.randomUUID().toString() private
WKT
final String WKT = "asWKT" static
WKTLiteral
final String WKTLiteral = "wktLiteral" static
XLINKHREF
final String XLINKHREF = "xlink:href" static private
XMLSchema
final String XMLSchema ="http://www.w3.org/2001/XMLSchema#" static